/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Room {
  'code' : string,
  'player1Joined' : boolean,
  'state' : RoomGameState,
  'player2Joined' : boolean,
  'phase' : string,
  'maxOvers' : bigint,
}
export interface RoomGameState {
  'inningsBreak' : boolean,
  'wickets1' : bigint,
  'wickets2' : bigint,
  'ballState' : string,
  'balls1' : bigint,
  'balls2' : bigint,
  'overs1' : bigint,
  'overs2' : bigint,
  'currentInnings' : bigint,
  'gameOver' : boolean,
  'lastEvent' : string,
  'runs1' : bigint,
  'runs2' : bigint,
}
export interface Score { 'player' : string, 'score' : bigint }
export interface _SERVICE {
  'createRoom' : ActorMethod<[bigint], string>,
  'getRoom' : ActorMethod<[string], [] | [Room]>,
  'getTopScores' : ActorMethod<[], Array<Score>>,
  'joinRoom' : ActorMethod<[string], boolean>,
  'listOpenRooms' : ActorMethod<[], Array<string>>,
  'quickMatch' : ActorMethod<[], string>,
  'submitScore' : ActorMethod<[string, bigint], undefined>,
  'updateRoomState' : ActorMethod<[string, RoomGameState], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];