/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const RoomGameState = IDL.Record({
  'inningsBreak' : IDL.Bool,
  'wickets1' : IDL.Nat,
  'wickets2' : IDL.Nat,
  'ballState' : IDL.Text,
  'balls1' : IDL.Nat,
  'balls2' : IDL.Nat,
  'overs1' : IDL.Nat,
  'overs2' : IDL.Nat,
  'currentInnings' : IDL.Nat,
  'gameOver' : IDL.Bool,
  'lastEvent' : IDL.Text,
  'runs1' : IDL.Nat,
  'runs2' : IDL.Nat,
});
export const Room = IDL.Record({
  'code' : IDL.Text,
  'player1Joined' : IDL.Bool,
  'state' : RoomGameState,
  'player2Joined' : IDL.Bool,
  'phase' : IDL.Text,
  'maxOvers' : IDL.Nat,
});
export const Score = IDL.Record({ 'player' : IDL.Text, 'score' : IDL.Nat });

export const idlService = IDL.Service({
  'createRoom' : IDL.Func([IDL.Nat], [IDL.Text], []),
  'getRoom' : IDL.Func([IDL.Text], [IDL.Opt(Room)], ['query']),
  'getTopScores' : IDL.Func([], [IDL.Vec(Score)], ['query']),
  'joinRoom' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'listOpenRooms' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'quickMatch' : IDL.Func([], [IDL.Text], []),
  'submitScore' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'updateRoomState' : IDL.Func([IDL.Text, RoomGameState], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const RoomGameState = IDL.Record({
    'inningsBreak' : IDL.Bool,
    'wickets1' : IDL.Nat,
    'wickets2' : IDL.Nat,
    'ballState' : IDL.Text,
    'balls1' : IDL.Nat,
    'balls2' : IDL.Nat,
    'overs1' : IDL.Nat,
    'overs2' : IDL.Nat,
    'currentInnings' : IDL.Nat,
    'gameOver' : IDL.Bool,
    'lastEvent' : IDL.Text,
    'runs1' : IDL.Nat,
    'runs2' : IDL.Nat,
  });
  const Room = IDL.Record({
    'code' : IDL.Text,
    'player1Joined' : IDL.Bool,
    'state' : RoomGameState,
    'player2Joined' : IDL.Bool,
    'phase' : IDL.Text,
    'maxOvers' : IDL.Nat,
  });
  const Score = IDL.Record({ 'player' : IDL.Text, 'score' : IDL.Nat });
  
  return IDL.Service({
    'createRoom' : IDL.Func([IDL.Nat], [IDL.Text], []),
    'getRoom' : IDL.Func([IDL.Text], [IDL.Opt(Room)], ['query']),
    'getTopScores' : IDL.Func([], [IDL.Vec(Score)], ['query']),
    'joinRoom' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'listOpenRooms' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'quickMatch' : IDL.Func([], [IDL.Text], []),
    'submitScore' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'updateRoomState' : IDL.Func([IDL.Text, RoomGameState], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };